# https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/config/_default/params.en.toml
# site description
description = "CXwudi's (âœ¨Otowa no YumeğŸŒ™) Personal Blog"
# site keywords
# keywords = ["Vocaloid", "Anime", "Java"] # commented out as not sure what is it for?

# Footer config
# é¡µé¢åº•éƒ¨ä¿¡æ¯é…ç½®
[footer]
  # Custom content (HTML format is supported)
  # è‡ªå®šä¹‰å†…å®¹ (æ”¯æŒ HTML æ ¼å¼)
  custom = '<div>Source - <a href="https://github.com/CXwudi/personal-blog-source" target="_blank" rel="noopener noreffer" title="/CXwudi/personal-blog-source" one-link-mark="yes"><i class="fab fa-github fa-fw"></i>GitHub</a></div>'
  # license info (HTML format is supported)
  # è®¸å¯åè®®ä¿¡æ¯ (æ”¯æŒ HTML æ ¼å¼)
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a>'

# Page config
# æ–‡ç« é¡µé¢é…ç½®
[page]
  # configure the link to report issue for the post
  # é…ç½®æäº¤é”™è¯¯çš„é“¾æ¥
  linkToReport = "https://github.com/CXwudi/personal-blog-source/discussions/new?category=content-issue-report&title=[issue]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|File|https://github.com/CXwudi/personal-blog-source/tree/main/content/{path}|%0A%0APlease%20describe%20your%20problem%20in%20detail.%0A%0AThank%20you%20for%20reporting%20the%20issue."
  # "https://github.com/CXwudi/personal-blog-source/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/CXwudi/personal-blog-source/tree/main/content/{path}|"
  # https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
  # https://gitlab.com/user/repo/-/issues/new?issue[title]=[bug]%20{title}&issue[description]=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://gitlab.com/user/repo/-/edit/main/{path}|
  # Comment config
  # è¯„è®ºç³»ç»Ÿè®¾ç½®
  [page.comment]
    # Waline comment config (https://waline.js.org)
    # Waline è¯„è®ºç³»ç»Ÿè®¾ç½® (https://waline.js.org)
    [page.comment.waline] 
      # emojis from https://waline.js.org/guide/client/emoji.html#%E9%A2%84%E8%AE%BE
      # and https://github.com/GamerNoTitle/Valine-Magic
      # the coding link for the emoji from GameNoTitle/Valine-Magic is not working,
      # we use æ¸ºè½¯å…¬ç›Š CDN from https://cdn.onmicrosoft.cn/
      emoji = [
        'https://jsd.onmicrosoft.cn/gh/walinejs/emojis@1.1.0/tw-emoji',
        'https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/Tieba-New', # has more emoji than waline's one
        'https://jsd.onmicrosoft.cn/gh/walinejs/emojis@1.1.0/qq',
        'https://jsd.onmicrosoft.cn/gh/walinejs/emojis@1.1.0/weibo',
        'https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/bilibilitv',
        'https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/Snow-Miku',
        'https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/Menhera-chan',
        ]
  
# Sponsor config
# èµåŠ©è®¾ç½®
[sponsor]
  bio = "I hope you enjoyed the content. Wish to see you again in next post."

# Search config
# æœç´¢é…ç½®
[search]
  # snippet length of the result
  # ç»“æœå†…å®¹ç‰‡æ®µé•¿åº¦
  snippetLength = 300