# https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/config/_default/params.en.toml
# site description
description = "CXwudi's (âœ¨Otowa no YumeğŸŒ™) Personal Blog"
# site keywords
# keywords = ["Vocaloid", "Anime", "Java"] # commented out as not sure what is it for?

# Footer config
# é¡µé¢åº•éƒ¨ä¿¡æ¯é…ç½®
[footer]
  # Custom content (HTML format is supported)
  # è‡ªå®šä¹‰å†…å®¹ (æ”¯æŒ HTML æ ¼å¼)
  custom = '<div>Source - <a href="https://github.com/CXwudi/personal-blog-source" target="_blank" rel="noopener noreffer" title="/CXwudi/personal-blog-source"><svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3 .3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5 .3-6.2 2.3zm44.2-1.7c-2.9 .7-4.9 2.6-4.6 4.9 .3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3 .7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3 .3 2.9 2.3 3.9 1.6 1 3.6 .7 4.3-.7 .7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3 .7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3 .7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"/></svg>GitHub</a></div>'
  # license info (HTML format is supported)
  # è®¸å¯åè®®ä¿¡æ¯ (æ”¯æŒ HTML æ ¼å¼)
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a>'

# Page config
# æ–‡ç« é¡µé¢é…ç½®
[page]
  # configure the link to report issue for the post
  # é…ç½®æäº¤é”™è¯¯çš„é“¾æ¥
  linkToReport = "https://github.com/CXwudi/personal-blog-source/discussions/new?category=content-issue-report&title=[issue]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|File|https://github.com/CXwudi/personal-blog-source/tree/main/content/{path}|%0A%0APlease%20describe%20your%20problem%20in%20detail.%0A%0AThank%20you%20for%20reporting%20the%20issue."
  # "https://github.com/CXwudi/personal-blog-source/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/CXwudi/personal-blog-source/tree/main/content/{path}|"
  # https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
  # https://gitlab.com/user/repo/-/issues/new?issue[title]=[bug]%20{title}&issue[description]=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://gitlab.com/user/repo/-/edit/main/{path}|
  # Comment config
  # è¯„è®ºç³»ç»Ÿè®¾ç½®
  [page.comment]
    # Waline comment config (https://waline.js.org)
    # Waline è¯„è®ºç³»ç»Ÿè®¾ç½® (https://waline.js.org)
    [page.comment.waline] 
      # emojis from https://waline.js.org/guide/client/emoji.html#%E9%A2%84%E8%AE%BE
      # and https://github.com/GamerNoTitle/Valine-Magic
      # the coding link for the emoji from GameNoTitle/Valine-Magic is not working,
      # we use https://fastly.jsdelivr.net/ and æ¸ºè½¯å…¬ç›Š CDN from https://cdn.onmicrosoft.cn/
      # both are accessible in china but fastly is better for other countries while æ¸ºè½¯å…¬ç›Š CDN is better for china
      emoji = [
        'https://fastly.jsdelivr.net/gh/walinejs/emojis@1.1.0/tw-emoji',
        'https://fastly.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Tieba-New', # has more emoji than waline's one
        'https://fastly.jsdelivr.net/gh/walinejs/emojis@1.1.0/qq',
        'https://fastly.jsdelivr.net/gh/walinejs/emojis@1.1.0/weibo',
        'https://fastly.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/bilibilitv',
        'https://fastly.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Snow-Miku',
        'https://fastly.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Menhera-chan',
        ]
  # Page SEO config
  # é¡µé¢ SEO é…ç½®
  [page.seo]
    # Publisher info
    # å‡ºç‰ˆè€…ä¿¡æ¯
    [page.seo.publisher]
      name = "CXwudi" # this must be consistent with the author name in data/authors/CXwudi.toml

# Sponsor config
# èµåŠ©è®¾ç½®
[sponsor]
  bio = "I hope you enjoyed the content. See you again in next post."

# Search config
# æœç´¢é…ç½®
[search]
  # snippet length of the result
  # ç»“æœå†…å®¹ç‰‡æ®µé•¿åº¦
  snippetLength = 300