# https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/config/_default/params.zh-cn.toml
description = "CXæ— æ•Œ(âœ¨éŸ³ç¾½ä¹‹æ¢¦ğŸŒ™)çš„ä¸ªäººåšå®¢"
# keywords = ["Anime", "Vocaloid", "Java"]


# Footer config
# é¡µé¢åº•éƒ¨ä¿¡æ¯é…ç½®
[footer]
  enable = true
  # Custom content (HTML format is supported)
  # è‡ªå®šä¹‰å†…å®¹ (æ”¯æŒ HTML æ ¼å¼)
  custom = '<div>æºç  - <a href="https://github.com/CXwudi/personal-blog-source" target="_blank" rel="noopener noreffer" title="/CXwudi/personal-blog-source" one-link-mark="yes"><i class="fab fa-github fa-fw"></i>GitHub</a></div>'
  # whether to show Hugo and theme info
  # æ˜¯å¦æ˜¾ç¤º Hugo å’Œä¸»é¢˜ä¿¡æ¯
  hugo = true
  # whether to show copyright info
  # æ˜¯å¦æ˜¾ç¤ºç‰ˆæƒä¿¡æ¯
  copyright = true
  # whether to show the author
  # æ˜¯å¦æ˜¾ç¤ºä½œè€…
  author = true
  # site creation time
  # ç½‘ç«™åˆ›ç«‹å¹´ä»½
  since = 2021
  # ICP info only in China (HTML format is supported)
  # ICP å¤‡æ¡ˆä¿¡æ¯ï¼Œä»…åœ¨ä¸­å›½ä½¿ç”¨ (æ”¯æŒ HTML æ ¼å¼)
  icp = ""
  # license info (HTML format is supported)
  # è®¸å¯åè®®ä¿¡æ¯ (æ”¯æŒ HTML æ ¼å¼)
  license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by/4.0/deed.zh" target="_blank">CC BY 4.0</a>'

# Page config
# æ–‡ç« é¡µé¢é…ç½®
[page]
  # whether to hide a page from home page
  # æ˜¯å¦åœ¨ä¸»é¡µéšè—ä¸€ç¯‡æ–‡ç« 
  hiddenFromHomePage = false
  # whether to hide a page from search results
  # æ˜¯å¦åœ¨æœç´¢ç»“æœä¸­éšè—ä¸€ç¯‡æ–‡ç« 
  hiddenFromSearch = false
  # whether to enable twemoji
  # æ˜¯å¦ä½¿ç”¨ twemoji
  twemoji = false
  # whether to enable lightgallery
  # æ˜¯å¦ä½¿ç”¨ lightgallery
  lightgallery = false
  # whether to enable the ruby extended syntax
  # æ˜¯å¦ä½¿ç”¨ ruby æ‰©å±•è¯­æ³•
  ruby = true
  # whether to enable the fraction extended syntax
  # æ˜¯å¦ä½¿ç”¨ fraction æ‰©å±•è¯­æ³•
  fraction = true
  # whether to enable the fontawesome extended syntax
  # æ˜¯å¦ä½¿ç”¨ fontawesome æ‰©å±•è¯­æ³•
  fontawesome = true
  # whether to show link to Raw Markdown content of the content
  # æ˜¯å¦æ˜¾ç¤ºåŸå§‹ Markdown æ–‡æ¡£å†…å®¹çš„é“¾æ¥
  linkToMarkdown = true
  # configure the link to view source the post
  # é…ç½®æ–‡ç« åŸå§‹æ–‡ä»¶çš„é“¾æ¥
  linkToSource = "https://github.com/CXwudi/personal-blog-source/tree/main/content/{path}"
  # "https://github.com/user/repo/blob/main/{path}"
  # configure the link to edit the post
  # é…ç½®ç¼–è¾‘æ–‡ç« çš„é“¾æ¥
  linkToEdit = "https://github.com/CXwudi/personal-blog-source/edit/main/content/{path}"
  # https://github.com/user/repo/edit/main/{path}
  # https://gitlab.com/user/repo/-/edit/main/{path}
  # https://bitbucket.org/user/repo/src/main/{path}?mode=edit
  # configure the link to report issue for the post
  # é…ç½®æäº¤é”™è¯¯çš„é“¾æ¥
  linkToReport = "https://github.com/CXwudi/personal-blog-source/discussions/new?title=[issue]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/CXwudi/personal-blog-source/tree/main/content/{path}|%0A%0APlease%20choose%20the%20proper%20category%20and%20describe%20the%20problem%20in%20detail.%0A%0AThank%20you%20for%20reporting%20the%20issue."
  # "https://github.com/CXwudi/personal-blog-source/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/CXwudi/personal-blog-source/tree/main/content/{path}|"
  # https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
  # https://gitlab.com/user/repo/-/issues/new?issue[title]=[bug]%20{title}&issue[description]=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://gitlab.com/user/repo/-/edit/main/{path}|
  # whether to show the full text content in RSS
  # æ˜¯å¦åœ¨ RSS ä¸­æ˜¾ç¤ºå…¨æ–‡å†…å®¹
  rssFullText = true
  # Page style ("normal", "wide")
  # é¡µé¢æ ·å¼ ("normal", "wide")
  pageStyle = "normal"
  # whether to enable series navigation
  # æ˜¯å¦ä½¿ç”¨ç³»åˆ—å¯¼èˆª
  seriesNavigation = true
  # Display a message at the beginning of an article to warn the reader that its content might be outdated.
  # åœ¨æ–‡ç« å¼€å¤´æ˜¾ç¤ºæç¤ºä¿¡æ¯ï¼Œæé†’è¯»è€…æ–‡ç« å†…å®¹å¯èƒ½è¿‡æ—¶ã€‚
  [page.outdatedArticleReminder]
    enable = false # let's make it false by default, we enable it explicitly on each article
    # Display the reminder if the last modified time is more than 180 days ago.
    # å¦‚æœæ–‡ç« æœ€åæ›´æ–°äºè¿™å¤©æ•°ä¹‹å‰ï¼Œæ˜¾ç¤ºæé†’
    reminder = 180
    # Display warning if the last modified time is more than 365 days ago.
    # å¦‚æœæ–‡ç« æœ€åæ›´æ–°äºè¿™å¤©æ•°ä¹‹å‰ï¼Œæ˜¾ç¤ºè­¦å‘Š
    warning = 365
  # Table of the contents config
  # ç›®å½•é…ç½®
  [page.toc]
    # whether to enable the table of the contents
    # æ˜¯å¦ä½¿ç”¨ç›®å½•
    enable = true
    # whether to keep the static table of the contents in front of the post
    # æ˜¯å¦ä¿æŒä½¿ç”¨æ–‡ç« å‰é¢çš„é™æ€ç›®å½•
    keepStatic = false
    # whether to make the table of the contents in the sidebar automatically collapsed
    # æ˜¯å¦ä½¿ä¾§è¾¹ç›®å½•è‡ªåŠ¨æŠ˜å å±•å¼€
    auto = true
  # Code config
  # ä»£ç é…ç½®
  [page.code]
    # whether to show the copy button of the code block
    # æ˜¯å¦æ˜¾ç¤ºä»£ç å—çš„å¤åˆ¶æŒ‰é’®
    copy = true
    # the maximum number of lines of displayed code by default
    # é»˜è®¤å±•å¼€æ˜¾ç¤ºçš„ä»£ç è¡Œæ•°
    maxShownLines = 10
  [page.table]
    # whether to enable sorting in the tables
    # æ˜¯å¦å¼€å¯è¡¨æ ¼æ’åº
    sort = true
  [page.header]
    # whether to enable auto header numbering
    # æ˜¯å¦å¼€å¯æ ‡é¢˜è‡ªåŠ¨ç¼–å·
    # [page.header.number]
    #   enable = true
    #   [page.header.number.format]
    #     h2 = "{h2}. {title}"
    #     h3 = "{h2}.{h3}. {title}"
    #     h4 = "{h2}.{h3}.{h4}. {title}"
    #     h5 = "{h2}.{h3}.{h4}.{h5}. {title}"
    #     h6 = "{h2}.{h3}.{h4}.{h5}.{h6}. {title}"
  [page.comment]
    enable = true
    [page.comment.waline]
      enable = true
      serverURL = "https://cxwudi-blog-waline.vercel.app"
      pageview = true
      comment = true
      # emojis from https://waline.js.org/guide/client/emoji.html#%E9%A2%84%E8%AE%BE
      # and https://github.com/GamerNoTitle/Valine-Magic
      # the coding link for the emoji from GameNoTitle/Valine-Magic is not working, hence using author's proxy
      # but we are unsure when would it break again. need to keep an eye on it
      emoji = [
        'https://cdn.bilicdn.tk/gh/GamerNoTitle/ValineCDN@master/Tieba-New', # re-ordered as chinese may prefer tieba emoji than twitter/discord emoji
        'https://unpkg.com/@waline/emojis@1.1.0/tw-emoji',
        'https://unpkg.com/@waline/emojis@1.1.0/qq',
        'https://unpkg.com/@waline/emojis@1.1.0/weibo',
        'https://cdn.bilicdn.tk/gh/GamerNoTitle/ValineCDN@master/Snow-Miku',
        'https://cdn.bilicdn.tk/gh/GamerNoTitle/ValineCDN@master/Menhera-chan',
        ]
      meta = ['nick', 'mail', 'link']
      requiredMeta = ['nick', 'mail']
      login = 'enabled' # use 'force' when we want to force the user to login to avoid spam, but so far let's just use requiredMeta
      wordLimit = 800  # we decide to put this limit to not let long strings break any system
      pageSize = 12
      imageUploader = false
      highlighter = true
      texRenderer = false
      # it looks like waline can now detect language automatically
  # Social share links in post page
  # æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
  [page.share]
    enable = true
    Baidu = false # is not available
    Blogger = false
    Buffer = false
    Digg = false
    Evernote = true
    Facebook = true
    Flipboard = false
    HackerNews = true
    Instapaper = false
    Line = true
    Linkedin = false
    Mix = false
    Myspace = false
    Odnoklassniki = false
    Pinterest = false
    Pocket = false
    Reddit = true
    Renren = false
    Skype = false
    Stumbleupon = false
    Telegram = true
    Trello = false
    Tumblr = false
    Twitter = true
    VK = false
    Weibo = true
    # Weixin API example: "https://tenapi.cn/qr/?txt="
    # https://docs.tenapi.cn/qrcode.html
    # https://www.free-api.com/doc/531
    # http://www.alapi.cn/api/view/72
    # OR self-hosted: https://github.com/yhf7952/QrCodeApi
    Weixin = "https://api.oick.cn/qrcode/api.php?size=130&text="
    Whatsapp = true
    Xing = false
  # Page SEO config
  # é¡µé¢ SEO é…ç½®
  [page.seo]
    # image URL
    # å›¾ç‰‡ URL
    images = []
    # Publisher info
    # å‡ºç‰ˆè€…ä¿¡æ¯
    [page.seo.publisher]
      name = "xxxx"
      logoUrl = "/avater/avatar 1 smaller file size.jpg"
  # Related content config
  # ç›¸å…³æ–‡ç« æ¨èé…ç½®
  [page.related]
    enable = false
    count = 5
    
# Sponsor config
# èµåŠ©è®¾ç½®
[sponsor]
  enable = false
  bio = "å¸Œæœ›æ‚¨å–œæ¬¢è¿™äº›å†…å®¹ã€‚æœŸå¾…ä¸ä½ åœ¨ä¸‹ä¸€ç¯‡æ–‡ç« ä¸­å†è§ã€‚"
  link = "https://ko-fi.com/mikufancx"
  custom = "<a href='https://ko-fi.com/mikufancx' target='_blank'><img height='54' style='border:0px;height:54px;' src='https://storage.ko-fi.com/cdn/brandasset/kofi_s_logo_nolabel.png' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>"

# Search config
# æœç´¢é…ç½®
[search]
  enable = true
  # type of search engine ("algolia", "fuse")
  # æœç´¢å¼•æ“çš„ç±»å‹ ("algolia", "fuse")
  type = "fuse"
  # max index length of the chunked content
  # æ–‡ç« å†…å®¹æœ€é•¿ç´¢å¼•é•¿åº¦
  contentLength = 4000
  # placeholder of the search bar
  # æœç´¢æ¡†çš„å ä½æç¤ºè¯­
  placeholder = ""
  # max number of results length
  # æœ€å¤§ç»“æœæ•°ç›®
  maxResultLength = 10
  # snippet length of the result
  # ç»“æœå†…å®¹ç‰‡æ®µé•¿åº¦
  snippetLength = 50
  # HTML tag name of the highlight part in results
  # æœç´¢ç»“æœä¸­é«˜äº®éƒ¨åˆ†çš„ HTML æ ‡ç­¾
  highlightTag = "em"
  # whether to use the absolute URL based on the baseURL in search index
  # æ˜¯å¦åœ¨æœç´¢ç´¢å¼•ä¸­ä½¿ç”¨åŸºäº baseURL çš„ç»å¯¹è·¯å¾„
  absoluteURL = false
  [search.algolia]
    index = "blog_zh_cn"
    appID = "9346ZAKTV2"
    searchKey = "7fdbdab62ae2a2f171c8cbea19ac38d6"
  [search.fuse]
    # https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.1
    distance = 100
    ignoreLocation = true
    useExtendedSearch = false
    ignoreFieldNorm = false