# Privacy config (https://gohugo.io/about/hugo-and-gdpr/)
# 隐私信息配置 (https://gohugo.io/about/hugo-and-gdpr/)
# https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/config/_default/privacy.toml

# privacy of the Google Analytics (replaced by params.analytics.google)
# Google Analytics 相关隐私 (被 params.analytics.google 替代)
[googleAnalytics]
  # ...
[twitter] # copied from sample site
  enableDNT = true
[youtube]
  privacyEnhanced = true
