baseURL = "http://example.org/"
theme = "DoIt"
defaultContentLanguage = "en"

[languages]
  [languages.en]
    weight = 1
    title = "âœ¨Otowa no YumeğŸŒ™ Personal Site"  
    languageCode = "en"
    languageName = "English"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
        weight = 1
      [[languages.en.menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.en.menu.main]]
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
        weight = 3
      [[languages.en.menu.main]]
        identifier = "series"
        pre = ""
        post = ""
        name = "Series"
        url = "/series/"
        title = ""
        weight = 4
        # let's hide this until we got a second author to avoid confusion
      # [[languages.en.menu.main]] 
      #   identifier = "authors"
      #   pre = ""
      #   post = ""
      #   name = "Authors"
      #   url = "/authors/"
      #   title = ""
      #   weight = 5
      [[languages.en.menu.main]]
        identifier = "about"
        pre = ""
        post = ""
        name = "About"
        url = "/about/"
        title = ""
        weight = 6
    [languages.en.params]
      # site description
      description = "CXwudi's (âœ¨Otowa no YumeğŸŒ™) Personal Site"
      # site keywords
      keywords = ["Vocaloid", "Anime", "Java"]
      # Home page config
      [languages.en.params.home]
        # amount of RSS pages
        rss = 10
        # Home page profile
        [languages.en.params.home.profile]
          enable = true
          # Gravatar Email for preferred avatar in home page
          gravatarEmail = "cx2010017@gmail.com"
          subtitle = "TODO: something to say"
          typeit = true
          social = true
      [languages.en.params.page.comment]
        enable = true
        [languages.en.params.page.comment.waline]
          enable = true
          serverURL = "https://waline-vercel-ijtw8zr98-cxwudi.vercel.app/"
          wordLimit = 0
          avatar = "mp"
          lang = "en"
          meta = ["nick", "mail", "link"]
          pageSize = 12
          visitor = true
          highlight = true
          requiredFields = []
          anonymous = false
      # Social share links in post page
      # æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
      [languages.en.params.page.share]
        enable = true
        Twitter = true
        Facebook = true
        Linkedin = false
        Whatsapp = false
        Pinterest = false
        Tumblr = false
        HackerNews = false
        Reddit = true
        VK = false
        Buffer = false
        Xing = false
        Line = true
        Instapaper = false
        Pocket = false
        Digg = false
        Stumbleupon = false
        Flipboard = false
        Weibo = true
        Renren = false
        Myspace = false
        Blogger = false
        Baidu = false # is not available
        Odnoklassniki = false
        Evernote = true
        Skype = true
        Trello = false
        Mix = false

  [languages.zh-cn]
    weight = 2
    title = "âœ¨éŸ³ç¾½ä¹‹æ¢¦ğŸŒ™ã®ä¸ªäººåšå®¢"  
    # language code, CN only here
    languageCode = "zh-CN"
    languageName = "ç®€ä½“ä¸­æ–‡"
    # whether to include Chinese/Japanese/Korean
    hasCJKLanguage = true
    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        identifier = "posts"
        pre = ""
        post = ""
        name = "æ‰€æœ‰æ–‡ç« "
        url = "/posts/"
        title = ""
        weight = 1
      [[languages.zh-cn.menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "æ ‡ç­¾"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.zh-cn.menu.main]]
        identifier = "categories"
        pre = ""
        post = ""
        name = "åˆ†ç±»"
        url = "/categories/"
        title = ""
        weight = 3
      [[languages.zh-cn.menu.main]]
        identifier = "series"
        pre = ""
        post = ""
        name = "ç³»åˆ—"
        url = "/series/"
        title = ""
        weight = 4
      # [[languages.zh-cn.menu.main]]
      #   identifier = "authors"
      #   pre = ""
      #   post = ""
      #   name = "ä½œè€…"
      #   url = "/authors/"
      #   title = ""
      #   weight = 5
      [[languages.zh-cn.menu.main]]
        identifier = "about"
        pre = ""
        post = ""
        name = "å…³äº"
        url = "/about/"
        title = ""
        weight = 6
    [languages.zh-cn.params]
      description = "âœ¨éŸ³ç¾½ä¹‹æ¢¦ğŸŒ™ã®ä¸ªäººåšå®¢"
      keywords = ["Anime", "Vocaloid", "Java"]
      [languages.zh-cn.params.home]
        rss = 10
        [languages.zh-cn.params.home.profile]
          enable = true
          gravatarEmail = "cx2010017@gmail.com"
          subtitle = "åº§å³é“­ï¼ˆTODOï¼‰"
          typeit = true
          social = true
      [languages.zh-cn.params.page.comment]
        enable = true
        [languages.zh-cn.params.page.comment.waline]
          enable = true
          serverURL = "https://waline-vercel-ijtw8zr98-cxwudi.vercel.app/"
          wordLimit = 0
          avatar = "mp"
          lang = "zh-cn"
          meta = ["nick", "mail", "link"]
          pageSize = 12
          visitor = true
          highlight = true
          requiredFields = []
          anonymous = false
      # Social share links in post page
      # æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
      [languages.zh-cn.params.page.share]
        enable = true
        Twitter = true
        Facebook = true
        Linkedin = false
        Whatsapp = false
        Pinterest = false
        Tumblr = false
        HackerNews = false
        Reddit = true
        VK = false
        Buffer = false
        Xing = false
        Line = true
        Instapaper = false
        Pocket = false
        Digg = false
        Stumbleupon = false
        Flipboard = false
        Weibo = true
        Renren = false
        Myspace = false
        Blogger = false
        Baidu = false
        Odnoklassniki = false
        Evernote = true
        Skype = true
        Trello = false
        Mix = false

# if you want some setting go i18n, 
# then all settings in same or sub module of that setting must go i18n
# e.g. the commenting system, the share button

[author] # no needed and use DoIt's multi authors
  name = "CXwudi"
  email = "charleschen0502@gmail.com"
  link = "https://linktr.ee/CXwudi"

[Permalinks]
  posts = ":year:month/:filename"
  # posts = ":filename"

[params]
  version = "0.2.X"
  title = "CXwudi's All-in-one Personal Site"

# Analytics config
# ç½‘ç«™åˆ†æé…ç½®
[params.analytics]
enable = false
  # Google Analytics
  [params.analytics.google]
    id = ""
    # whether to anonymize IP
    # æ˜¯å¦åŒ¿ååŒ–ç”¨æˆ· IP
    anonymizeIP = true
  # Fathom Analytics
  [params.analytics.fathom]
    id = ""
    # server url for your tracker if you're self hosting
    # è‡ªè¡Œæ‰˜ç®¡è¿½è¸ªå™¨æ—¶çš„ä¸»æœºè·¯å¾„
    server = ""

# Footer config
# é¡µé¢åº•éƒ¨ä¿¡æ¯é…ç½®
[params.footer]
  enable = true
  # Custom content (HTML format is supported)
  # è‡ªå®šä¹‰å†…å®¹ (æ”¯æŒ HTML æ ¼å¼)
  custom = ''
  # whether to show Hugo and theme info
  # æ˜¯å¦æ˜¾ç¤º Hugo å’Œä¸»é¢˜ä¿¡æ¯
  hugo = true
  # whether to show copyright info
  # æ˜¯å¦æ˜¾ç¤ºç‰ˆæƒä¿¡æ¯
  copyright = true
  # whether to show the author
  # æ˜¯å¦æ˜¾ç¤ºä½œè€…
  author = true
  # site creation time
  # ç½‘ç«™åˆ›ç«‹å¹´ä»½
  since = 2021
  # ICP info only in China (HTML format is supported)
  # ICP å¤‡æ¡ˆä¿¡æ¯ï¼Œä»…åœ¨ä¸­å›½ä½¿ç”¨ (æ”¯æŒ HTML æ ¼å¼)
  icp = ""
  # license info (HTML format is supported)
  # è®¸å¯åè®®ä¿¡æ¯ (æ”¯æŒ HTML æ ¼å¼)
  license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# Page config
# æ–‡ç« é¡µé¢é…ç½®
[params.page]
  # whether to enable the ruby extended syntax
  # æ˜¯å¦ä½¿ç”¨ ruby æ‰©å±•è¯­æ³•
  ruby = true
  # whether to enable the fraction extended syntax
  # æ˜¯å¦ä½¿ç”¨ fraction æ‰©å±•è¯­æ³•
  fraction = true
  # whether to enable the fontawesome extended syntax
  # æ˜¯å¦ä½¿ç”¨ fontawesome æ‰©å±•è¯­æ³•
  fontawesome = true
  # whether to show link to Raw Markdown content of the content
  # æ˜¯å¦æ˜¾ç¤ºåŸå§‹ Markdown æ–‡æ¡£å†…å®¹çš„é“¾æ¥
  linkToMarkdown = true
  # whether to show the full text content in RSS
  # æ˜¯å¦åœ¨ RSS ä¸­æ˜¾ç¤ºå…¨æ–‡å†…å®¹
  rssFullText = true
  # Page style ("normal", "wide")
  # é¡µé¢æ ·å¼ ("normal", "wide")
  pageStyle = "wide"


# Header config
# é¡µé¢å¤´éƒ¨å¯¼èˆªæ é…ç½®
[params.header]
  # theme change mode ("switch", "select")
  # ä¸»é¢˜åˆ‡æ¢æ¨¡å¼ ("switch", "select")
  themeChangeMode = "select"

[params.search] # copied from sample site
  enable = true
  type = "fuse"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 30
  highlightTag = "em"
  absoluteURL = false

# ä¸»é¡µçš„ç¤¾äº¤ä¿¡æ¯è®¾ç½®
[params.social]
  linktree = "CXwudi"
  Email = "charleschen0502@gmail.com"
  RSS = true

[privacy] # copied from sample site
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false 

[outputs] # copied from sample site
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[outputFormats.MarkDown] # copied from sample site, needed for MarkDown
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false
[mediaTypes] # copied from sample site, needed for mediaType "text/plain"
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options for taxonomies
# ç”¨äºåˆ†ç±»çš„è®¾ç½®, å¾ˆé‡è¦
[taxonomies]
  author = "authors" # don't remove, can make clicking authors return 404
  category = "categories"
  tag = "tags"
  series = "series" # need it to make series works properly